export const salesData = [
  {
    title1: "ENS Linked",
    title2: "ENS Linked",
    textColour: "#4BDFFF",
    blurColour: "#25B5D51A",
    name: "dingaling.eth",
    time: "2 months ago",
    Icon: "/Assets/Dingaling.svg",
    amount: 1.82,
    xp: 200,
  },
  {
    title1: "Best Flip",
    title2: "Sold",
    textColour: "#FFC148",
    blurColour: "#F8A9101A",
    name: "CryptoPunk #2131",
    time: "10 days ago",
    Icon: "/Assets/Cryptopunk.svg",
    amount: 98.5,
    xp: 150,
  },
  {
    title1: "Should have sold",
    title2: "Mint",
    textColour: "#44FFC8",
    blurColour: "#0BF1AD1A",
    name: "Rare Apepe #6974",
    time: "10 days ago",
    Icon: "/Assets/RareApepe.svg",
    amount: 98.5,
    xp: 200,
  },
  {
    title1: "First NFT bought",
    title2: "Bought",
    textColour: "#4BDFFF",
    blurColour: "#25B5D51A",
    name: "BAYC #7925",
    time: "10 days ago",
    Icon: "/Assets/BAYC.svg",
    amount: 98.5,
    xp: 10,
  },
  {
    title1: "Paper Handed",
    title2: "Sold",
    textColour: "#44FFC8",
    blurColour: "#0BF1AD1A",
    name: "Moonbird #7866",
    time: "10 days ago",
    Icon: "/Assets/Moonbird2.svg",
    amount: 98.5,
    xp: 200,
  },
];
